[book]
authors = ["RustTT.org"]
language = "en"
multilingual = false
src = "src"


[output.html]
git-repository-url = "https://github.com/studyrs/rusttt"
edit-url-template = "https://github.com/studyrs/rusttt-book/edit/main/{path}"

additional-css = ["theme/style.css"]
additional-js = ["assets/custom.js"]